// Generated by scripts/generate-reader-types.mjs.
// Source: docs/openapi/ai-content-v1.json
// DO NOT EDIT MANUALLY. Run `npm run generate:reader-types`.

export type PluginState = "READY" | "UNAVAILABLE" | "DISABLED" | "QUARANTINED"

export type McpState = "CONTRACT_READY_TRANSPORT_UNAVAILABLE"

export type AiSummaryStyle = "CONCISE" | "BALANCED" | "DETAILED"

export interface AiSummaryConfig {
  enabled: boolean
  providerId: string
  style: AiSummaryStyle
  maxOutputTokens: number
}

export interface AiTranslationConfig {
  enabled: boolean
  providerId: string
  defaultTargetLocale: string
  maxOutputTokens: number
}

export interface AiConfig {
  revision: number
  isEnabled: boolean
  summary: AiSummaryConfig
  translation: AiTranslationConfig
}

export interface AiConfigEnvelope {
  pluginState: PluginState
  mcpState: McpState
  config: AiConfig | null
}

export interface PutAiConfigRequest {
  expectedRevision: number | null
  isEnabled: boolean
  summary: AiSummaryConfig
  translation: AiTranslationConfig
}

export type AiAvailability = "READY" | "NOT_CONFIGURED" | "DISABLED" | "PROVIDER_UNAVAILABLE" | "PLUGIN_UNAVAILABLE"

export type AiOperationState = "UNAVAILABLE" | "DISABLED" | "IDLE" | "QUEUED" | "RUNNING" | "RETRY_WAIT" | "SUCCEEDED" | "FAILED"

export interface AiJob {
  jobId: string
  status: AiJobStatus
  attempts: number
  maxAttempts: AiJobMaxAttempts
  nextAttemptAt: string
  lastErrorCode: string | null
  createdAt: string
  startedAt: string | null
  completedAt: string | null
}

export type AiJobStatus = "QUEUED" | "RUNNING" | "RETRY_WAIT" | "SUCCEEDED" | "FAILED"

export type AiJobMaxAttempts = 3

export interface AiSummaryArtifact {
  artifactId: string
  kind: AiSummaryArtifactKind
  providerLabel: string
  createdAt: string
  sourceLanguage: string
  summary: string
  bullets: string[]
  conclusion: string | null
}

export type AiSummaryArtifactKind = "AI_SUMMARY"

export interface AiTranslationArtifact {
  artifactId: string
  kind: AiTranslationArtifactKind
  providerLabel: string
  createdAt: string
  detectedSourceLanguage: string
  targetLocale: string
  title: string
  bodyMarkdown: string
}

export type AiTranslationArtifactKind = "AI_TRANSLATION"

export type AiArtifact = AiSummaryArtifact | AiTranslationArtifact

export interface AiOperationOverview {
  operation: AiOperationOverviewOperation
  targetLocale?: string
  state: AiOperationState
  job: AiJob | null
  artifact: AiArtifact | null
}

export type AiOperationOverviewOperation = "SUMMARIZE" | "TRANSLATE"

export interface EntryAiOverview {
  availability: AiAvailability
  mcpState: McpState
  summary: AiOperationOverview
  translation: AiOperationOverview
}

export interface EnqueueAiJobRequest {
  operation: EnqueueAiJobRequestOperation
  targetLocale: string | null
  idempotencyKey: string
}

export type EnqueueAiJobRequestOperation = "SUMMARIZE" | "TRANSLATE"

export interface RetryAiJobRequest {
  idempotencyKey: string
}

export interface ApiError {
  code: string
  message: string
  fields?: Record<string, string>
  requestId: string
}

export interface ApiErrorEnvelope {
  error: ApiError
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function hasOwn(value: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(value, key)
}

function hasOnlyKeys(value: Record<string, unknown>, keys: readonly string[]): boolean {
  return Object.keys(value).every((key) => keys.includes(key))
}

function isUuid(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
}

function isUri(value: string): boolean {
  try {
    return new URL(value).protocol.length > 0
  } catch {
    return false
  }
}

export function isPluginState(value: unknown): value is PluginState {
  return (value === "READY" || value === "UNAVAILABLE" || value === "DISABLED" || value === "QUARANTINED")
}

export function isMcpState(value: unknown): value is McpState {
  return (value === "CONTRACT_READY_TRANSPORT_UNAVAILABLE")
}

export function isAiSummaryStyle(value: unknown): value is AiSummaryStyle {
  return (value === "CONCISE" || value === "BALANCED" || value === "DETAILED")
}

export function isAiSummaryConfig(value: unknown): value is AiSummaryConfig {
  return ((isRecord(value) && hasOnlyKeys(value, ["enabled","providerId","style","maxOutputTokens"]) && hasOwn(value, "enabled") && (typeof value["enabled"] === "boolean") && hasOwn(value, "providerId") && ((typeof value["providerId"] === "string" && isUuid(value["providerId"]))) && hasOwn(value, "style") && isAiSummaryStyle(value["style"]) && hasOwn(value, "maxOutputTokens") && ((typeof value["maxOutputTokens"] === "number" && Number.isFinite(value["maxOutputTokens"]) && Number.isInteger(value["maxOutputTokens"]) && value["maxOutputTokens"] >= 128 && value["maxOutputTokens"] <= 4096))))
}

export function isAiTranslationConfig(value: unknown): value is AiTranslationConfig {
  return ((isRecord(value) && hasOnlyKeys(value, ["enabled","providerId","defaultTargetLocale","maxOutputTokens"]) && hasOwn(value, "enabled") && (typeof value["enabled"] === "boolean") && hasOwn(value, "providerId") && ((typeof value["providerId"] === "string" && isUuid(value["providerId"]))) && hasOwn(value, "defaultTargetLocale") && ((typeof value["defaultTargetLocale"] === "string" && value["defaultTargetLocale"].length >= 2 && value["defaultTargetLocale"].length <= 64)) && hasOwn(value, "maxOutputTokens") && ((typeof value["maxOutputTokens"] === "number" && Number.isFinite(value["maxOutputTokens"]) && Number.isInteger(value["maxOutputTokens"]) && value["maxOutputTokens"] >= 256 && value["maxOutputTokens"] <= 16384))))
}

export function isAiConfig(value: unknown): value is AiConfig {
  return ((isRecord(value) && hasOnlyKeys(value, ["revision","isEnabled","summary","translation"]) && hasOwn(value, "revision") && ((typeof value["revision"] === "number" && Number.isFinite(value["revision"]) && Number.isInteger(value["revision"]) && value["revision"] >= 0)) && hasOwn(value, "isEnabled") && (typeof value["isEnabled"] === "boolean") && hasOwn(value, "summary") && isAiSummaryConfig(value["summary"]) && hasOwn(value, "translation") && isAiTranslationConfig(value["translation"])))
}

export function isAiConfigEnvelope(value: unknown): value is AiConfigEnvelope {
  return ((isRecord(value) && hasOnlyKeys(value, ["pluginState","mcpState","config"]) && hasOwn(value, "pluginState") && isPluginState(value["pluginState"]) && hasOwn(value, "mcpState") && isMcpState(value["mcpState"]) && hasOwn(value, "config") && (isAiConfig(value["config"]) || (value["config"] === null))))
}

export function isPutAiConfigRequest(value: unknown): value is PutAiConfigRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["expectedRevision","isEnabled","summary","translation"]) && hasOwn(value, "expectedRevision") && ((typeof value["expectedRevision"] === "number" && Number.isFinite(value["expectedRevision"]) && Number.isInteger(value["expectedRevision"]) && value["expectedRevision"] >= 0) || value["expectedRevision"] === null) && hasOwn(value, "isEnabled") && (typeof value["isEnabled"] === "boolean") && hasOwn(value, "summary") && isAiSummaryConfig(value["summary"]) && hasOwn(value, "translation") && isAiTranslationConfig(value["translation"])))
}

export function isAiAvailability(value: unknown): value is AiAvailability {
  return (value === "READY" || value === "NOT_CONFIGURED" || value === "DISABLED" || value === "PROVIDER_UNAVAILABLE" || value === "PLUGIN_UNAVAILABLE")
}

export function isAiOperationState(value: unknown): value is AiOperationState {
  return (value === "UNAVAILABLE" || value === "DISABLED" || value === "IDLE" || value === "QUEUED" || value === "RUNNING" || value === "RETRY_WAIT" || value === "SUCCEEDED" || value === "FAILED")
}

export function isAiJob(value: unknown): value is AiJob {
  return ((isRecord(value) && hasOnlyKeys(value, ["jobId","status","attempts","maxAttempts","nextAttemptAt","lastErrorCode","createdAt","startedAt","completedAt"]) && hasOwn(value, "jobId") && ((typeof value["jobId"] === "string" && isUuid(value["jobId"]))) && hasOwn(value, "status") && (value["status"] === "QUEUED" || value["status"] === "RUNNING" || value["status"] === "RETRY_WAIT" || value["status"] === "SUCCEEDED" || value["status"] === "FAILED") && hasOwn(value, "attempts") && ((typeof value["attempts"] === "number" && Number.isFinite(value["attempts"]) && Number.isInteger(value["attempts"]) && value["attempts"] >= 0 && value["attempts"] <= 3)) && hasOwn(value, "maxAttempts") && (value["maxAttempts"] === 3) && hasOwn(value, "nextAttemptAt") && ((typeof value["nextAttemptAt"] === "string")) && hasOwn(value, "lastErrorCode") && ((typeof value["lastErrorCode"] === "string" && value["lastErrorCode"].length <= 64) || value["lastErrorCode"] === null) && hasOwn(value, "createdAt") && ((typeof value["createdAt"] === "string")) && hasOwn(value, "startedAt") && ((typeof value["startedAt"] === "string") || value["startedAt"] === null) && hasOwn(value, "completedAt") && ((typeof value["completedAt"] === "string") || value["completedAt"] === null)))
}

export function isAiSummaryArtifact(value: unknown): value is AiSummaryArtifact {
  return ((isRecord(value) && hasOnlyKeys(value, ["artifactId","kind","providerLabel","createdAt","sourceLanguage","summary","bullets","conclusion"]) && hasOwn(value, "artifactId") && ((typeof value["artifactId"] === "string" && isUuid(value["artifactId"]))) && hasOwn(value, "kind") && (value["kind"] === "AI_SUMMARY") && hasOwn(value, "providerLabel") && ((typeof value["providerLabel"] === "string" && value["providerLabel"].length >= 1 && value["providerLabel"].length <= 200)) && hasOwn(value, "createdAt") && ((typeof value["createdAt"] === "string")) && hasOwn(value, "sourceLanguage") && ((typeof value["sourceLanguage"] === "string" && value["sourceLanguage"].length >= 2 && value["sourceLanguage"].length <= 64)) && hasOwn(value, "summary") && ((typeof value["summary"] === "string" && value["summary"].length <= 65536)) && hasOwn(value, "bullets") && ((Array.isArray(value["bullets"]) && value["bullets"].length <= 8 && value["bullets"].every((item1) => ((typeof item1 === "string" && item1.length <= 8192))))) && hasOwn(value, "conclusion") && ((typeof value["conclusion"] === "string" && value["conclusion"].length <= 16384) || value["conclusion"] === null)))
}

export function isAiTranslationArtifact(value: unknown): value is AiTranslationArtifact {
  return ((isRecord(value) && hasOnlyKeys(value, ["artifactId","kind","providerLabel","createdAt","detectedSourceLanguage","targetLocale","title","bodyMarkdown"]) && hasOwn(value, "artifactId") && ((typeof value["artifactId"] === "string" && isUuid(value["artifactId"]))) && hasOwn(value, "kind") && (value["kind"] === "AI_TRANSLATION") && hasOwn(value, "providerLabel") && ((typeof value["providerLabel"] === "string" && value["providerLabel"].length >= 1 && value["providerLabel"].length <= 200)) && hasOwn(value, "createdAt") && ((typeof value["createdAt"] === "string")) && hasOwn(value, "detectedSourceLanguage") && ((typeof value["detectedSourceLanguage"] === "string" && value["detectedSourceLanguage"].length >= 2 && value["detectedSourceLanguage"].length <= 64)) && hasOwn(value, "targetLocale") && ((typeof value["targetLocale"] === "string" && value["targetLocale"].length >= 2 && value["targetLocale"].length <= 64)) && hasOwn(value, "title") && ((typeof value["title"] === "string" && value["title"].length <= 16384)) && hasOwn(value, "bodyMarkdown") && ((typeof value["bodyMarkdown"] === "string" && value["bodyMarkdown"].length <= 262144))))
}

export function isAiArtifact(value: unknown): value is AiArtifact {
  return (isAiSummaryArtifact(value) || isAiTranslationArtifact(value))
}

export function isAiOperationOverview(value: unknown): value is AiOperationOverview {
  return ((isRecord(value) && hasOnlyKeys(value, ["operation","targetLocale","state","job","artifact"]) && hasOwn(value, "operation") && (value["operation"] === "SUMMARIZE" || value["operation"] === "TRANSLATE") && (!hasOwn(value, "targetLocale") || ((typeof value["targetLocale"] === "string" && value["targetLocale"].length >= 2 && value["targetLocale"].length <= 64))) && hasOwn(value, "state") && isAiOperationState(value["state"]) && hasOwn(value, "job") && (isAiJob(value["job"]) || (value["job"] === null)) && hasOwn(value, "artifact") && (isAiArtifact(value["artifact"]) || (value["artifact"] === null))))
}

export function isEntryAiOverview(value: unknown): value is EntryAiOverview {
  return ((isRecord(value) && hasOnlyKeys(value, ["availability","mcpState","summary","translation"]) && hasOwn(value, "availability") && isAiAvailability(value["availability"]) && hasOwn(value, "mcpState") && isMcpState(value["mcpState"]) && hasOwn(value, "summary") && isAiOperationOverview(value["summary"]) && hasOwn(value, "translation") && isAiOperationOverview(value["translation"])))
}

export function isEnqueueAiJobRequest(value: unknown): value is EnqueueAiJobRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["operation","targetLocale","idempotencyKey"]) && hasOwn(value, "operation") && (value["operation"] === "SUMMARIZE" || value["operation"] === "TRANSLATE") && hasOwn(value, "targetLocale") && ((typeof value["targetLocale"] === "string" && value["targetLocale"].length >= 2 && value["targetLocale"].length <= 64) || value["targetLocale"] === null) && hasOwn(value, "idempotencyKey") && ((typeof value["idempotencyKey"] === "string" && value["idempotencyKey"].length >= 1 && value["idempotencyKey"].length <= 255 && new RegExp("^[!-~]+$").test(value["idempotencyKey"])))))
}

export function isRetryAiJobRequest(value: unknown): value is RetryAiJobRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["idempotencyKey"]) && hasOwn(value, "idempotencyKey") && ((typeof value["idempotencyKey"] === "string" && value["idempotencyKey"].length >= 1 && value["idempotencyKey"].length <= 255 && new RegExp("^[!-~]+$").test(value["idempotencyKey"])))))
}

export function isApiError(value: unknown): value is ApiError {
  return ((isRecord(value) && hasOnlyKeys(value, ["code","message","fields","requestId"]) && hasOwn(value, "code") && ((typeof value["code"] === "string")) && hasOwn(value, "message") && ((typeof value["message"] === "string")) && (!hasOwn(value, "fields") || ((isRecord(value["fields"]) && Object.entries(value["fields"]).every(([entry1, item1]) => ((typeof item1 === "string")))))) && hasOwn(value, "requestId") && ((typeof value["requestId"] === "string" && isUuid(value["requestId"])))))
}

export function isApiErrorEnvelope(value: unknown): value is ApiErrorEnvelope {
  return ((isRecord(value) && hasOnlyKeys(value, ["error"]) && hasOwn(value, "error") && isApiError(value["error"])))
}
