import { emitValidators } from "./validator-emitter.mjs"

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

export function emitTypes(document, sourcePath, publicAliases = {}) {
  const schemas = document?.components?.schemas
  if (!isObject(schemas)) {
    throw new Error(`${sourcePath} must define components.schemas`)
  }

  const aliases = collectEnumAliases(schemas)
  const blocks = []
  for (const [name, schema] of Object.entries(schemas)) {
    blocks.push(emitDeclaration(name, schema, aliases))
    const schemaAliases = aliases.get(name)
    if (schemaAliases) {
      for (const alias of schemaAliases.values()) {
        blocks.push(`export type ${alias.name} = ${alias.type}`)
      }
    }
  }
  for (const [alias, target] of Object.entries(publicAliases)) {
    if (!Object.hasOwn(schemas, target)) {
      throw new Error(`${sourcePath} cannot alias missing schema ${target}`)
    }
    blocks.push(`export type ${alias} = ${target}`)
  }
  blocks.push(emitValidators(schemas, publicAliases))

  return [
    "// Generated by scripts/generate-reader-types.mjs.",
    `// Source: ${sourcePath}`,
    "// DO NOT EDIT MANUALLY. Run `npm run generate:reader-types`.",
    "",
    blocks.join("\n\n"),
    "",
  ].join("\n")
}

function emitDeclaration(name, schema, aliases) {
  if (!isObject(schema)) throw new Error(`${name} must be a schema object`)
  if (isObjectSchema(schema)) {
    const choices = requiredChoices(schema)
    if (choices) return emitConstrainedObject(name, schema, aliases.get(name), choices)
    return emitInterface(name, schema, aliases.get(name))
  }
  return `export type ${name} = ${emitType(schema, `${name}`, undefined)}`
}

function emitConstrainedObject(name, schema, aliases, choices) {
  const properties = schema.properties ?? {}
  const required = new Set(Array.isArray(schema.required) ? schema.required : [])
  const fields = Object.entries(properties).map(([field, fieldSchema]) => {
    const key = IDENTIFIER.test(field) ? field : JSON.stringify(field)
    const alias = aliases?.get(field)?.name
    return `  ${key}${required.has(field) ? "" : "?"}: ${emitType(fieldSchema, `${name}.${field}`, alias)}`
  })
  const alternatives = choices.map((choice) => {
    const choiceFields = choice.map((field) => {
      const fieldSchema = properties[field]
      if (!isObject(fieldSchema)) throw new Error(`${name}.anyOf requires unknown field ${field}`)
      const key = IDENTIFIER.test(field) ? field : JSON.stringify(field)
      const alias = aliases?.get(field)?.name
      return `${key}: ${emitType(fieldSchema, `${name}.${field}`, alias)}`
    })
    return `  | { ${choiceFields.join("; ")} }`
  })
  return [`export type ${name} = {`, ...fields, "} & (", ...alternatives, ")"].join("\n")
}

function requiredChoices(schema) {
  if (!Array.isArray(schema.anyOf) || schema.anyOf.length === 0) return null
  const choices = []
  for (const candidate of schema.anyOf) {
    if (
      !isObject(candidate) ||
      !Array.isArray(candidate.required) ||
      candidate.required.length === 0 ||
      Object.keys(candidate).some((key) => key !== "required")
    ) {
      return null
    }
    choices.push(candidate.required)
  }
  return choices
}

function emitInterface(name, schema, aliases) {
  const properties = schema.properties ?? {}
  if (!isObject(properties)) throw new Error(`${name}.properties must be an object`)
  const required = new Set(Array.isArray(schema.required) ? schema.required : [])
  const fields = Object.entries(properties).map(([field, fieldSchema]) => {
    const key = IDENTIFIER.test(field) ? field : JSON.stringify(field)
    const optional = required.has(field) ? "" : "?"
    const alias = aliases?.get(field)?.name
    return `  ${key}${optional}: ${emitType(fieldSchema, `${name}.${field}`, alias)}`
  })
  return [`export interface ${name} {`, ...fields, "}"].join("\n")
}

function emitType(schema, path, enumAlias) {
  if (!isObject(schema)) throw new Error(`${path} must be a schema object`)
  if (typeof schema.$ref === "string") return localRefName(schema.$ref, path)
  if (enumAlias) return enumAlias

  if (Array.isArray(schema.enum)) return emitEnum(schema.enum, path)
  if (Array.isArray(schema.anyOf) && !isObjectSchema(schema)) {
    return joinUnion(schema.anyOf.map((item, index) => emitType(item, `${path}.anyOf[${index}]`)))
  }

  const types = Array.isArray(schema.type) ? schema.type : [schema.type]
  const emitted = types.filter(Boolean).map((type) => emitPrimitiveType(type, schema, path))
  if (emitted.length > 0) return joinUnion(emitted)
  if (isObjectSchema(schema)) return emitAnonymousObject(schema, path)
  throw new Error(`${path} uses an unsupported schema shape`)
}

function emitPrimitiveType(type, schema, path) {
  switch (type) {
    case "null":
      return "null"
    case "string":
      return "string"
    case "integer":
    case "number":
      return "number"
    case "boolean":
      return "boolean"
    case "array": {
      if (!isObject(schema.items)) throw new Error(`${path}.items must be a schema object`)
      const item = emitType(schema.items, `${path}.items`)
      return `${needsParentheses(item) ? `(${item})` : item}[]`
    }
    case "object":
      return emitAnonymousObject(schema, path)
    default:
      throw new Error(`${path} uses unsupported type ${JSON.stringify(type)}`)
  }
}

function emitAnonymousObject(schema, path) {
  if (isObject(schema.properties)) {
    const required = new Set(Array.isArray(schema.required) ? schema.required : [])
    const fields = Object.entries(schema.properties).map(([field, fieldSchema]) => {
      const key = IDENTIFIER.test(field) ? field : JSON.stringify(field)
      return `${key}${required.has(field) ? "" : "?"}: ${emitType(fieldSchema, `${path}.${field}`)}`
    })
    return fields.length === 0 ? "Record<string, never>" : `{ ${fields.join("; ")} }`
  }
  if (isObject(schema.additionalProperties)) {
    return `Record<string, ${emitType(schema.additionalProperties, `${path}.additionalProperties`)}>`
  }
  return "Record<string, unknown>"
}

function collectEnumAliases(schemas) {
  const aliases = new Map()
  for (const [schemaName, schema] of Object.entries(schemas)) {
    if (!isObject(schema?.properties)) continue
    const schemaAliases = new Map()
    for (const [field, fieldSchema] of Object.entries(schema.properties)) {
      if (isObject(fieldSchema) && Array.isArray(fieldSchema.enum)) {
        schemaAliases.set(field, {
          name: `${schemaName}${pascalCase(field)}`,
          type: emitEnum(fieldSchema.enum, `${schemaName}.${field}`),
        })
      }
    }
    if (schemaAliases.size > 0) aliases.set(schemaName, schemaAliases)
  }
  return aliases
}

function emitEnum(values, path) {
  if (values.length === 0) throw new Error(`${path}.enum must not be empty`)
  return joinUnion(
    values.map((value) => {
      if (value === null) return "null"
      if (["string", "number", "boolean"].includes(typeof value)) {
        return JSON.stringify(value)
      }
      throw new Error(`${path}.enum contains an unsupported value`)
    }),
  )
}

function localRefName(reference, path) {
  const prefix = "#/components/schemas/"
  if (!reference.startsWith(prefix)) {
    throw new Error(`${path} uses unsupported reference ${reference}`)
  }
  return reference.slice(prefix.length)
}

function joinUnion(types) {
  return [...new Set(types)].join(" | ")
}

function needsParentheses(type) {
  return type.includes(" | ") || type.startsWith("{ ")
}

function pascalCase(value) {
  return value
    .replace(/(^|[^A-Za-z0-9]+)([A-Za-z0-9])/g, (_match, _prefix, letter) =>
      letter.toUpperCase(),
    )
    .replace(/[^A-Za-z0-9_$]/g, "")
}

function isObjectSchema(schema) {
  const types = Array.isArray(schema.type) ? schema.type : [schema.type]
  return types.includes("object") || isObject(schema.properties)
}

function isObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}
