import { setupI18n } from "@lingui/core"

export type AppLocale = "zh-CN" | "en"

const catalogs: Record<AppLocale, Record<string, string>> = {
  "zh-CN": {
    "app.loading": "正在准备 Raindrop",
    "app.loadError": "无法加载 Raindrop",
    "app.loadErrorDescription": "请检查服务连接后刷新页面。",
    "setup.eyebrow": "首次启动",
    "setup.title": "开始设置 Raindrop",
    "setup.contextTitle": "把阅读数据留在自己的服务器上",
    "setup.description": "连接数据库并创建首位管理员。设置完成后，此入口会自动关闭。",
    "setup.continue": "继续设置",
    "setup.progress": "设置进度",
    "setup.databaseTitle": "连接数据库",
    "setup.databaseDescription": "SQLite 适合单机部署，也可以连接现有的 PostgreSQL 或 MySQL。",
    "setup.token": "设置令牌",
    "setup.tokenDescription": "输入 Raindrop 启动时打印在终端中的一次性令牌。",
    "setup.databaseType": "数据库类型",
    "setup.databaseUrl": "数据库 URL",
    "setup.databaseUrlDescription": "连接信息只发送给当前 Raindrop 实例。",
    "setup.databaseCheck": "检查数据库并继续",
    "setup.databaseChecking": "正在检查数据库",
    "setup.databaseError": "数据库连接失败",
    "setup.adminTitle": "创建管理员",
    "setup.adminDescription": "这个账号拥有实例管理权限，后续可以再添加普通用户和 OIDC。",
    "setup.username": "用户名",
    "setup.email": "邮箱",
    "setup.password": "密码",
    "setup.passwordDescription": "至少 12 个字节，建议使用密码管理器生成。",
    "setup.back": "返回数据库",
    "setup.complete": "完成设置",
    "setup.completing": "正在创建管理员",
    "setup.completeError": "无法完成设置",
    "setup.required": "此字段为必填项。",
    "setup.usernameInvalid": "用户名需要包含 3 到 64 个非空白字符。",
    "setup.emailInvalid": "请输入有效的邮箱地址。",
    "setup.passwordInvalid": "密码至少需要 12 个字节。",
    "setup.environmentHint": "环境托管部署也可以设置",
    "login.eyebrow": "Raindrop 阅读器",
    "login.title": "欢迎回来",
    "login.contextTitle": "一个安静、私有的阅读工作区",
    "login.description": "登录后继续处理未读文章。",
    "login.continue": "登录",
    "login.username": "用户名或邮箱",
    "login.password": "密码",
    "login.error": "登录失败",
    "login.errorDescription": "请检查用户名、邮箱或密码后重试。",
    "common.language": "语言",
    "common.logout": "退出登录",
    "common.menu": "打开菜单",
    "ready.title": "阅读空间已就绪",
    "ready.description": "订阅与文章功能将在下一阶段接入。",
  },
  en: {
    "app.loading": "Preparing Raindrop",
    "app.loadError": "Raindrop could not load",
    "app.loadErrorDescription": "Check the service connection and refresh the page.",
    "setup.eyebrow": "First run",
    "setup.title": "Set up Raindrop",
    "setup.contextTitle": "Keep your reading data on your own server",
    "setup.description":
      "Connect a database and create the first administrator. This entry closes when setup finishes.",
    "setup.continue": "Continue setup",
    "setup.progress": "Setup progress",
    "setup.databaseTitle": "Connect a database",
    "setup.databaseDescription":
      "SQLite fits a single-node install, or connect an existing PostgreSQL or MySQL database.",
    "setup.token": "Setup token",
    "setup.tokenDescription": "Enter the one-time token printed when Raindrop started.",
    "setup.databaseType": "Database type",
    "setup.databaseUrl": "Database URL",
    "setup.databaseUrlDescription": "Connection details are sent only to this Raindrop instance.",
    "setup.databaseCheck": "Check database and continue",
    "setup.databaseChecking": "Checking database",
    "setup.databaseError": "Database connection failed",
    "setup.adminTitle": "Create the administrator",
    "setup.adminDescription":
      "This account can manage the instance. Add regular users and OIDC after setup.",
    "setup.username": "Username",
    "setup.email": "Email",
    "setup.password": "Password",
    "setup.passwordDescription": "Use at least 12 bytes, preferably generated by a password manager.",
    "setup.back": "Back to database",
    "setup.complete": "Complete setup",
    "setup.completing": "Creating administrator",
    "setup.completeError": "Setup could not be completed",
    "setup.required": "This field is required.",
    "setup.usernameInvalid": "Use 3 to 64 characters without spaces.",
    "setup.emailInvalid": "Enter a valid email address.",
    "setup.passwordInvalid": "Use a password of at least 12 bytes.",
    "setup.environmentHint": "Environment-managed installs can also set",
    "login.eyebrow": "Raindrop reader",
    "login.title": "Welcome back",
    "login.contextTitle": "A quiet, private workspace for reading",
    "login.description": "Sign in to continue with your unread articles.",
    "login.continue": "Sign in",
    "login.username": "Username or email",
    "login.password": "Password",
    "login.error": "Sign-in failed",
    "login.errorDescription": "Check your username, email, or password and try again.",
    "common.language": "Language",
    "common.logout": "Sign out",
    "common.menu": "Open menu",
    "ready.title": "Your reading space is ready",
    "ready.description": "Subscriptions and articles arrive in the next foundation slice.",
  },
}

export const i18n = setupI18n()

export function activateLocale(locale: AppLocale) {
  i18n.load(locale, catalogs[locale])
  i18n.activate(locale)
  document.documentElement.lang = locale
}

export function detectLocale(): AppLocale {
  return navigator.language.toLowerCase().startsWith("zh") ? "zh-CN" : "en"
}

activateLocale(detectLocale())
