// Generated by scripts/generate-reader-types.mjs.
// Source: docs/openapi/translation-v2.json
// DO NOT EDIT MANUALLY. Run `npm run generate:reader-types`.

export type TranslationEngine = "OPENAI" | "DEEPLX"

export type TranslationDisplayMode = "TRANSLATION_ONLY" | "BILINGUAL" | "HOVER" | "SIDE_BY_SIDE"

export type AiTranslationProfile = "GENERAL" | "TECHNICAL" | "LITERARY" | "ACADEMIC" | "BUSINESS" | "SOCIAL_NEWS" | "CUSTOM"

export interface OpenAiTranslationConfig {
  providerId: string | null
  maxOutputTokens: number
  profile: AiTranslationProfile
  customSystemPrompt: string | null
  customPrompt: string | null
}

export interface DeepLxTranslationConfig {
  displayName: string
  description: string | null
  baseUrl: string | null
  hasApiKey: boolean
}

export interface TranslationConfig {
  engine: TranslationEngine
  displayMode: TranslationDisplayMode
  isEnabled: boolean
  defaultTargetLocale: string
  openAi: OpenAiTranslationConfig
  deepLx: DeepLxTranslationConfig
  revision: number | null
}

export interface OpenAiTranslationConfigRequest {
  providerId: string | null
  maxOutputTokens: number
  profile: AiTranslationProfile
  customSystemPrompt: string | null
  customPrompt: string | null
}

export interface DeepLxTranslationConfigRequest {
  displayName: string
  description: string | null
  baseUrl: string | null
  apiKey?: string | null
}

export interface PutTranslationConfigRequest {
  expectedRevision: number | null
  engine: TranslationEngine
  displayMode: TranslationDisplayMode
  isEnabled: boolean
  defaultTargetLocale: string
  openAi: OpenAiTranslationConfigRequest
  deepLx: DeepLxTranslationConfigRequest
}

export interface TestDeepLxRequest {
  baseUrl: string | null
  apiKey?: string | null
}

export interface TestTranslationRequest {
  engine: TranslationEngine
  targetLocale: string
  openAi: OpenAiTranslationConfigRequest
  deepLx: TestDeepLxRequest
}

export interface TranslationTestResult {
  translatedText: string
  providerLabel: string
  detectedSourceLocale: string | null
  targetLocale: string
}

export interface TranslationSegment {
  index: number
  originalText: string
  translatedText: string
}

export interface TranslationResult {
  title: string
  segments: TranslationSegment[]
  providerLabel: string
  detectedSourceLocale: string | null
  targetLocale: string
}

export interface LookupRequest {
  text: string
}

export interface LookupExample {
  source: string
  target: string
}

export interface LookupResult {
  query: string
  translation: string
  definition: string | null
  examples: LookupExample[]
  providerLabel: string
  detectedSourceLocale: string | null
  targetLocale: string
}

export interface ApiError {
  code: string
  message: string
  fields?: Record<string, string>
  requestId: string
}

export interface ApiErrorEnvelope {
  error: ApiError
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function hasOwn(value: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(value, key)
}

function hasOnlyKeys(value: Record<string, unknown>, keys: readonly string[]): boolean {
  return Object.keys(value).every((key) => keys.includes(key))
}

function isUuid(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
}

function isUri(value: string): boolean {
  try {
    return new URL(value).protocol.length > 0
  } catch {
    return false
  }
}

export function isTranslationEngine(value: unknown): value is TranslationEngine {
  return (value === "OPENAI" || value === "DEEPLX")
}

export function isTranslationDisplayMode(value: unknown): value is TranslationDisplayMode {
  return (value === "TRANSLATION_ONLY" || value === "BILINGUAL" || value === "HOVER" || value === "SIDE_BY_SIDE")
}

export function isAiTranslationProfile(value: unknown): value is AiTranslationProfile {
  return (value === "GENERAL" || value === "TECHNICAL" || value === "LITERARY" || value === "ACADEMIC" || value === "BUSINESS" || value === "SOCIAL_NEWS" || value === "CUSTOM")
}

export function isOpenAiTranslationConfig(value: unknown): value is OpenAiTranslationConfig {
  return ((isRecord(value) && hasOnlyKeys(value, ["providerId","maxOutputTokens","profile","customSystemPrompt","customPrompt"]) && hasOwn(value, "providerId") && ((typeof value["providerId"] === "string" && isUuid(value["providerId"])) || value["providerId"] === null) && hasOwn(value, "maxOutputTokens") && ((typeof value["maxOutputTokens"] === "number" && Number.isFinite(value["maxOutputTokens"]) && Number.isInteger(value["maxOutputTokens"]) && value["maxOutputTokens"] >= 256 && value["maxOutputTokens"] <= 16384)) && hasOwn(value, "profile") && isAiTranslationProfile(value["profile"]) && hasOwn(value, "customSystemPrompt") && ((typeof value["customSystemPrompt"] === "string" && value["customSystemPrompt"].length <= 8192) || value["customSystemPrompt"] === null) && hasOwn(value, "customPrompt") && ((typeof value["customPrompt"] === "string" && value["customPrompt"].length <= 8192) || value["customPrompt"] === null)))
}

export function isDeepLxTranslationConfig(value: unknown): value is DeepLxTranslationConfig {
  return ((isRecord(value) && hasOnlyKeys(value, ["displayName","description","baseUrl","hasApiKey"]) && hasOwn(value, "displayName") && ((typeof value["displayName"] === "string" && value["displayName"].length >= 1 && value["displayName"].length <= 80)) && hasOwn(value, "description") && ((typeof value["description"] === "string" && value["description"].length <= 500) || value["description"] === null) && hasOwn(value, "baseUrl") && ((typeof value["baseUrl"] === "string" && value["baseUrl"].length <= 2048) || value["baseUrl"] === null) && hasOwn(value, "hasApiKey") && (typeof value["hasApiKey"] === "boolean")))
}

export function isTranslationConfig(value: unknown): value is TranslationConfig {
  return ((isRecord(value) && hasOnlyKeys(value, ["engine","displayMode","isEnabled","defaultTargetLocale","openAi","deepLx","revision"]) && hasOwn(value, "engine") && isTranslationEngine(value["engine"]) && hasOwn(value, "displayMode") && isTranslationDisplayMode(value["displayMode"]) && hasOwn(value, "isEnabled") && (typeof value["isEnabled"] === "boolean") && hasOwn(value, "defaultTargetLocale") && ((typeof value["defaultTargetLocale"] === "string" && value["defaultTargetLocale"].length >= 2 && value["defaultTargetLocale"].length <= 35)) && hasOwn(value, "openAi") && isOpenAiTranslationConfig(value["openAi"]) && hasOwn(value, "deepLx") && isDeepLxTranslationConfig(value["deepLx"]) && hasOwn(value, "revision") && ((typeof value["revision"] === "number" && Number.isFinite(value["revision"]) && Number.isInteger(value["revision"]) && value["revision"] >= 0) || value["revision"] === null)))
}

export function isOpenAiTranslationConfigRequest(value: unknown): value is OpenAiTranslationConfigRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["providerId","maxOutputTokens","profile","customSystemPrompt","customPrompt"]) && hasOwn(value, "providerId") && ((typeof value["providerId"] === "string" && isUuid(value["providerId"])) || value["providerId"] === null) && hasOwn(value, "maxOutputTokens") && ((typeof value["maxOutputTokens"] === "number" && Number.isFinite(value["maxOutputTokens"]) && Number.isInteger(value["maxOutputTokens"]) && value["maxOutputTokens"] >= 256 && value["maxOutputTokens"] <= 16384)) && hasOwn(value, "profile") && isAiTranslationProfile(value["profile"]) && hasOwn(value, "customSystemPrompt") && ((typeof value["customSystemPrompt"] === "string" && value["customSystemPrompt"].length <= 8192) || value["customSystemPrompt"] === null) && hasOwn(value, "customPrompt") && ((typeof value["customPrompt"] === "string" && value["customPrompt"].length <= 8192) || value["customPrompt"] === null)))
}

export function isDeepLxTranslationConfigRequest(value: unknown): value is DeepLxTranslationConfigRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["displayName","description","baseUrl","apiKey"]) && hasOwn(value, "displayName") && ((typeof value["displayName"] === "string" && value["displayName"].length >= 1 && value["displayName"].length <= 80)) && hasOwn(value, "description") && ((typeof value["description"] === "string" && value["description"].length <= 500) || value["description"] === null) && hasOwn(value, "baseUrl") && ((typeof value["baseUrl"] === "string" && value["baseUrl"].length <= 2048) || value["baseUrl"] === null) && (!hasOwn(value, "apiKey") || ((typeof value["apiKey"] === "string" && value["apiKey"].length <= 1024) || value["apiKey"] === null))))
}

export function isPutTranslationConfigRequest(value: unknown): value is PutTranslationConfigRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["expectedRevision","engine","displayMode","isEnabled","defaultTargetLocale","openAi","deepLx"]) && hasOwn(value, "expectedRevision") && ((typeof value["expectedRevision"] === "number" && Number.isFinite(value["expectedRevision"]) && Number.isInteger(value["expectedRevision"]) && value["expectedRevision"] >= 0) || value["expectedRevision"] === null) && hasOwn(value, "engine") && isTranslationEngine(value["engine"]) && hasOwn(value, "displayMode") && isTranslationDisplayMode(value["displayMode"]) && hasOwn(value, "isEnabled") && (typeof value["isEnabled"] === "boolean") && hasOwn(value, "defaultTargetLocale") && ((typeof value["defaultTargetLocale"] === "string" && value["defaultTargetLocale"].length >= 2 && value["defaultTargetLocale"].length <= 35)) && hasOwn(value, "openAi") && isOpenAiTranslationConfigRequest(value["openAi"]) && hasOwn(value, "deepLx") && isDeepLxTranslationConfigRequest(value["deepLx"])))
}

export function isTestDeepLxRequest(value: unknown): value is TestDeepLxRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["baseUrl","apiKey"]) && hasOwn(value, "baseUrl") && ((typeof value["baseUrl"] === "string" && value["baseUrl"].length <= 2048) || value["baseUrl"] === null) && (!hasOwn(value, "apiKey") || ((typeof value["apiKey"] === "string" && value["apiKey"].length <= 1024) || value["apiKey"] === null))))
}

export function isTestTranslationRequest(value: unknown): value is TestTranslationRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["engine","targetLocale","openAi","deepLx"]) && hasOwn(value, "engine") && isTranslationEngine(value["engine"]) && hasOwn(value, "targetLocale") && ((typeof value["targetLocale"] === "string" && value["targetLocale"].length >= 2 && value["targetLocale"].length <= 35)) && hasOwn(value, "openAi") && isOpenAiTranslationConfigRequest(value["openAi"]) && hasOwn(value, "deepLx") && isTestDeepLxRequest(value["deepLx"])))
}

export function isTranslationTestResult(value: unknown): value is TranslationTestResult {
  return ((isRecord(value) && hasOnlyKeys(value, ["translatedText","providerLabel","detectedSourceLocale","targetLocale"]) && hasOwn(value, "translatedText") && ((typeof value["translatedText"] === "string" && value["translatedText"].length >= 1 && value["translatedText"].length <= 65536)) && hasOwn(value, "providerLabel") && ((typeof value["providerLabel"] === "string" && value["providerLabel"].length >= 1 && value["providerLabel"].length <= 200)) && hasOwn(value, "detectedSourceLocale") && ((typeof value["detectedSourceLocale"] === "string" && value["detectedSourceLocale"].length <= 35) || value["detectedSourceLocale"] === null) && hasOwn(value, "targetLocale") && ((typeof value["targetLocale"] === "string" && value["targetLocale"].length >= 2 && value["targetLocale"].length <= 35))))
}

export function isTranslationSegment(value: unknown): value is TranslationSegment {
  return ((isRecord(value) && hasOnlyKeys(value, ["index","originalText","translatedText"]) && hasOwn(value, "index") && ((typeof value["index"] === "number" && Number.isFinite(value["index"]) && Number.isInteger(value["index"]) && value["index"] >= 0 && value["index"] <= 95)) && hasOwn(value, "originalText") && ((typeof value["originalText"] === "string" && value["originalText"].length >= 1 && value["originalText"].length <= 24000)) && hasOwn(value, "translatedText") && ((typeof value["translatedText"] === "string" && value["translatedText"].length >= 1 && value["translatedText"].length <= 65536))))
}

export function isTranslationResult(value: unknown): value is TranslationResult {
  return ((isRecord(value) && hasOnlyKeys(value, ["title","segments","providerLabel","detectedSourceLocale","targetLocale"]) && hasOwn(value, "title") && ((typeof value["title"] === "string" && value["title"].length >= 1 && value["title"].length <= 16384)) && hasOwn(value, "segments") && ((Array.isArray(value["segments"]) && value["segments"].length >= 1 && value["segments"].length <= 96 && value["segments"].every((item1) => isTranslationSegment(item1)))) && hasOwn(value, "providerLabel") && ((typeof value["providerLabel"] === "string" && value["providerLabel"].length >= 1 && value["providerLabel"].length <= 200)) && hasOwn(value, "detectedSourceLocale") && ((typeof value["detectedSourceLocale"] === "string" && value["detectedSourceLocale"].length <= 35) || value["detectedSourceLocale"] === null) && hasOwn(value, "targetLocale") && ((typeof value["targetLocale"] === "string" && value["targetLocale"].length >= 2 && value["targetLocale"].length <= 35))))
}

export function isLookupRequest(value: unknown): value is LookupRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["text"]) && hasOwn(value, "text") && ((typeof value["text"] === "string" && value["text"].length >= 1 && value["text"].length <= 200))))
}

export function isLookupExample(value: unknown): value is LookupExample {
  return ((isRecord(value) && hasOnlyKeys(value, ["source","target"]) && hasOwn(value, "source") && ((typeof value["source"] === "string" && value["source"].length >= 1 && value["source"].length <= 2048)) && hasOwn(value, "target") && ((typeof value["target"] === "string" && value["target"].length >= 1 && value["target"].length <= 2048))))
}

export function isLookupResult(value: unknown): value is LookupResult {
  return ((isRecord(value) && hasOnlyKeys(value, ["query","translation","definition","examples","providerLabel","detectedSourceLocale","targetLocale"]) && hasOwn(value, "query") && ((typeof value["query"] === "string" && value["query"].length >= 1 && value["query"].length <= 200)) && hasOwn(value, "translation") && ((typeof value["translation"] === "string" && value["translation"].length >= 1 && value["translation"].length <= 4096)) && hasOwn(value, "definition") && ((typeof value["definition"] === "string" && value["definition"].length <= 4096) || value["definition"] === null) && hasOwn(value, "examples") && ((Array.isArray(value["examples"]) && value["examples"].length <= 3 && value["examples"].every((item1) => isLookupExample(item1)))) && hasOwn(value, "providerLabel") && ((typeof value["providerLabel"] === "string" && value["providerLabel"].length >= 1 && value["providerLabel"].length <= 200)) && hasOwn(value, "detectedSourceLocale") && ((typeof value["detectedSourceLocale"] === "string" && value["detectedSourceLocale"].length <= 35) || value["detectedSourceLocale"] === null) && hasOwn(value, "targetLocale") && ((typeof value["targetLocale"] === "string" && value["targetLocale"].length >= 2 && value["targetLocale"].length <= 35))))
}

export function isApiError(value: unknown): value is ApiError {
  return ((isRecord(value) && hasOnlyKeys(value, ["code","message","fields","requestId"]) && hasOwn(value, "code") && ((typeof value["code"] === "string")) && hasOwn(value, "message") && ((typeof value["message"] === "string")) && (!hasOwn(value, "fields") || ((isRecord(value["fields"]) && Object.entries(value["fields"]).every(([entry1, item1]) => ((typeof item1 === "string")))))) && hasOwn(value, "requestId") && ((typeof value["requestId"] === "string" && isUuid(value["requestId"])))))
}

export function isApiErrorEnvelope(value: unknown): value is ApiErrorEnvelope {
  return ((isRecord(value) && hasOnlyKeys(value, ["error"]) && hasOwn(value, "error") && isApiError(value["error"])))
}
