// Generated by scripts/generate-reader-types.mjs.
// Source: docs/openapi/profile-v2.json
// DO NOT EDIT MANUALLY. Run `npm run generate:reader-types`.

export interface UserProfile {
  userId: string
  username: string
  displayName: string | null
  email: string | null
}

export type PatchUserProfileRequest = {
  displayName?: string | null
  email?: string | null
} & (
  | { displayName: string | null }
  | { email: string | null }
)

export interface ApiError {
  code: string
  message: string
  fields?: Record<string, string>
  requestId: string
}

export interface ApiErrorEnvelope {
  error: ApiError
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function hasOwn(value: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(value, key)
}

function hasOnlyKeys(value: Record<string, unknown>, keys: readonly string[]): boolean {
  return Object.keys(value).every((key) => keys.includes(key))
}

function isUuid(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
}

function isUri(value: string): boolean {
  try {
    return new URL(value).protocol.length > 0
  } catch {
    return false
  }
}

export function isUserProfile(value: unknown): value is UserProfile {
  return ((isRecord(value) && hasOnlyKeys(value, ["userId","username","displayName","email"]) && hasOwn(value, "userId") && ((typeof value["userId"] === "string" && isUuid(value["userId"]))) && hasOwn(value, "username") && ((typeof value["username"] === "string" && value["username"].length >= 3 && value["username"].length <= 64)) && hasOwn(value, "displayName") && ((typeof value["displayName"] === "string" && value["displayName"].length >= 1 && value["displayName"].length <= 80) || value["displayName"] === null) && hasOwn(value, "email") && ((typeof value["email"] === "string" && value["email"].length >= 3 && value["email"].length <= 320) || value["email"] === null)))
}

export function isPatchUserProfileRequest(value: unknown): value is PatchUserProfileRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["displayName","email"]) && Object.keys(value).length >= 1 && (!hasOwn(value, "displayName") || ((typeof value["displayName"] === "string" && value["displayName"].length <= 80) || value["displayName"] === null)) && (!hasOwn(value, "email") || ((typeof value["email"] === "string" && value["email"].length <= 320) || value["email"] === null))))
}

export function isApiError(value: unknown): value is ApiError {
  return ((isRecord(value) && hasOnlyKeys(value, ["code","message","fields","requestId"]) && hasOwn(value, "code") && ((typeof value["code"] === "string")) && hasOwn(value, "message") && ((typeof value["message"] === "string")) && (!hasOwn(value, "fields") || ((isRecord(value["fields"]) && Object.entries(value["fields"]).every(([entry1, item1]) => ((typeof item1 === "string")))))) && hasOwn(value, "requestId") && ((typeof value["requestId"] === "string" && isUuid(value["requestId"])))))
}

export function isApiErrorEnvelope(value: unknown): value is ApiErrorEnvelope {
  return ((isRecord(value) && hasOnlyKeys(value, ["error"]) && hasOwn(value, "error") && isApiError(value["error"])))
}
