// Generated by scripts/generate-reader-types.mjs.
// Source: docs/openapi/preferences-v2.json
// DO NOT EDIT MANUALLY. Run `npm run generate:reader-types`.

export interface UserPreferences {
  locale: UserPreferencesLocale
  themeMode: UserPreferencesThemeMode
  layoutDensity: UserPreferencesLayoutDensity
  readingFontScale: number
  readingFontFamily: UserPreferencesReadingFontFamily
  readingColorScheme: UserPreferencesReadingColorScheme
  linkOpenMode: UserPreferencesLinkOpenMode
}

export type UserPreferencesLocale = "zh-CN" | "en"

export type UserPreferencesThemeMode = "SYSTEM" | "LIGHT" | "DARK"

export type UserPreferencesLayoutDensity = "COMPACT" | "BALANCED" | "SPACIOUS"

export type UserPreferencesReadingFontFamily = "SERIF" | "SANS"

export type UserPreferencesReadingColorScheme = "AUTO" | "PAPER" | "SEPIA" | "GRAY"

export type UserPreferencesLinkOpenMode = "CURRENT_TAB" | "NEW_TAB"

export type PatchUserPreferencesRequest = {
  locale?: PatchUserPreferencesRequestLocale
  themeMode?: PatchUserPreferencesRequestThemeMode
  layoutDensity?: PatchUserPreferencesRequestLayoutDensity
  readingFontScale?: number
  readingFontFamily?: PatchUserPreferencesRequestReadingFontFamily
  readingColorScheme?: PatchUserPreferencesRequestReadingColorScheme
  linkOpenMode?: PatchUserPreferencesRequestLinkOpenMode
} & (
  | { locale: PatchUserPreferencesRequestLocale }
  | { themeMode: PatchUserPreferencesRequestThemeMode }
  | { layoutDensity: PatchUserPreferencesRequestLayoutDensity }
  | { readingFontScale: number }
  | { readingFontFamily: PatchUserPreferencesRequestReadingFontFamily }
  | { readingColorScheme: PatchUserPreferencesRequestReadingColorScheme }
  | { linkOpenMode: PatchUserPreferencesRequestLinkOpenMode }
)

export type PatchUserPreferencesRequestLocale = "zh-CN" | "en"

export type PatchUserPreferencesRequestThemeMode = "SYSTEM" | "LIGHT" | "DARK"

export type PatchUserPreferencesRequestLayoutDensity = "COMPACT" | "BALANCED" | "SPACIOUS"

export type PatchUserPreferencesRequestReadingFontFamily = "SERIF" | "SANS"

export type PatchUserPreferencesRequestReadingColorScheme = "AUTO" | "PAPER" | "SEPIA" | "GRAY"

export type PatchUserPreferencesRequestLinkOpenMode = "CURRENT_TAB" | "NEW_TAB"

export interface ApiError {
  code: string
  message: string
  fields?: Record<string, string>
  requestId: string
}

export interface ApiErrorEnvelope {
  error: ApiError
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function hasOwn(value: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(value, key)
}

function hasOnlyKeys(value: Record<string, unknown>, keys: readonly string[]): boolean {
  return Object.keys(value).every((key) => keys.includes(key))
}

function isUuid(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
}

function isUri(value: string): boolean {
  try {
    return new URL(value).protocol.length > 0
  } catch {
    return false
  }
}

export function isUserPreferences(value: unknown): value is UserPreferences {
  return ((isRecord(value) && hasOnlyKeys(value, ["locale","themeMode","layoutDensity","readingFontScale","readingFontFamily","readingColorScheme","linkOpenMode"]) && hasOwn(value, "locale") && (value["locale"] === "zh-CN" || value["locale"] === "en") && hasOwn(value, "themeMode") && (value["themeMode"] === "SYSTEM" || value["themeMode"] === "LIGHT" || value["themeMode"] === "DARK") && hasOwn(value, "layoutDensity") && (value["layoutDensity"] === "COMPACT" || value["layoutDensity"] === "BALANCED" || value["layoutDensity"] === "SPACIOUS") && hasOwn(value, "readingFontScale") && ((typeof value["readingFontScale"] === "number" && Number.isFinite(value["readingFontScale"]) && Number.isInteger(value["readingFontScale"]) && value["readingFontScale"] >= 85 && value["readingFontScale"] <= 130)) && hasOwn(value, "readingFontFamily") && (value["readingFontFamily"] === "SERIF" || value["readingFontFamily"] === "SANS") && hasOwn(value, "readingColorScheme") && (value["readingColorScheme"] === "AUTO" || value["readingColorScheme"] === "PAPER" || value["readingColorScheme"] === "SEPIA" || value["readingColorScheme"] === "GRAY") && hasOwn(value, "linkOpenMode") && (value["linkOpenMode"] === "CURRENT_TAB" || value["linkOpenMode"] === "NEW_TAB")))
}

export function isPatchUserPreferencesRequest(value: unknown): value is PatchUserPreferencesRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["locale","themeMode","layoutDensity","readingFontScale","readingFontFamily","readingColorScheme","linkOpenMode"]) && Object.keys(value).length >= 1 && (!hasOwn(value, "locale") || (value["locale"] === "zh-CN" || value["locale"] === "en")) && (!hasOwn(value, "themeMode") || (value["themeMode"] === "SYSTEM" || value["themeMode"] === "LIGHT" || value["themeMode"] === "DARK")) && (!hasOwn(value, "layoutDensity") || (value["layoutDensity"] === "COMPACT" || value["layoutDensity"] === "BALANCED" || value["layoutDensity"] === "SPACIOUS")) && (!hasOwn(value, "readingFontScale") || ((typeof value["readingFontScale"] === "number" && Number.isFinite(value["readingFontScale"]) && Number.isInteger(value["readingFontScale"]) && value["readingFontScale"] >= 85 && value["readingFontScale"] <= 130))) && (!hasOwn(value, "readingFontFamily") || (value["readingFontFamily"] === "SERIF" || value["readingFontFamily"] === "SANS")) && (!hasOwn(value, "readingColorScheme") || (value["readingColorScheme"] === "AUTO" || value["readingColorScheme"] === "PAPER" || value["readingColorScheme"] === "SEPIA" || value["readingColorScheme"] === "GRAY")) && (!hasOwn(value, "linkOpenMode") || (value["linkOpenMode"] === "CURRENT_TAB" || value["linkOpenMode"] === "NEW_TAB"))))
}

export function isApiError(value: unknown): value is ApiError {
  return ((isRecord(value) && hasOnlyKeys(value, ["code","message","fields","requestId"]) && hasOwn(value, "code") && ((typeof value["code"] === "string")) && hasOwn(value, "message") && ((typeof value["message"] === "string")) && (!hasOwn(value, "fields") || ((isRecord(value["fields"]) && Object.entries(value["fields"]).every(([entry1, item1]) => ((typeof item1 === "string")))))) && hasOwn(value, "requestId") && ((typeof value["requestId"] === "string" && isUuid(value["requestId"])))))
}

export function isApiErrorEnvelope(value: unknown): value is ApiErrorEnvelope {
  return ((isRecord(value) && hasOnlyKeys(value, ["error"]) && hasOwn(value, "error") && isApiError(value["error"])))
}
