// Generated by scripts/generate-reader-types.mjs.
// Source: docs/openapi/organization-v1.json
// DO NOT EDIT MANUALLY. Run `npm run generate:reader-types`.

export interface Category {
  categoryId: string
  title: string
  position: number
}

export interface CategoryList {
  items: Category[]
}

export interface CreateCategoryRequest {
  title: string
}

export type UpdateCategoryRequest = {
  title?: string
  position?: number
} & (
  | { title: string }
  | { position: number }
)

export interface ApiError {
  code: string
  message: string
  fields?: Record<string, string>
  requestId: string
}

export interface ApiErrorEnvelope {
  error: ApiError
}

export type CategoryResponse = Category

export type CategoryListResponse = CategoryList

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function hasOwn(value: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(value, key)
}

function hasOnlyKeys(value: Record<string, unknown>, keys: readonly string[]): boolean {
  return Object.keys(value).every((key) => keys.includes(key))
}

function isUuid(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
}

function isUri(value: string): boolean {
  try {
    return new URL(value).protocol.length > 0
  } catch {
    return false
  }
}

export function isCategory(value: unknown): value is Category {
  return ((isRecord(value) && hasOnlyKeys(value, ["categoryId","title","position"]) && hasOwn(value, "categoryId") && ((typeof value["categoryId"] === "string" && isUuid(value["categoryId"]))) && hasOwn(value, "title") && ((typeof value["title"] === "string" && value["title"].length >= 1 && value["title"].length <= 80)) && hasOwn(value, "position") && ((typeof value["position"] === "number" && Number.isFinite(value["position"]) && Number.isInteger(value["position"]) && value["position"] >= 0))))
}

export function isCategoryList(value: unknown): value is CategoryList {
  return ((isRecord(value) && hasOnlyKeys(value, ["items"]) && hasOwn(value, "items") && ((Array.isArray(value["items"]) && value["items"].length <= 250 && value["items"].every((item1) => isCategory(item1))))))
}

export function isCreateCategoryRequest(value: unknown): value is CreateCategoryRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["title"]) && hasOwn(value, "title") && ((typeof value["title"] === "string" && value["title"].length >= 1 && value["title"].length <= 80))))
}

export function isUpdateCategoryRequest(value: unknown): value is UpdateCategoryRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["title","position"]) && (!hasOwn(value, "title") || ((typeof value["title"] === "string" && value["title"].length >= 1 && value["title"].length <= 80))) && (!hasOwn(value, "position") || ((typeof value["position"] === "number" && Number.isFinite(value["position"]) && Number.isInteger(value["position"]) && value["position"] >= 0))))) && ((isRecord(value) && hasOwn(value, "title")) || (isRecord(value) && hasOwn(value, "position")))
}

export function isApiError(value: unknown): value is ApiError {
  return ((isRecord(value) && hasOnlyKeys(value, ["code","message","fields","requestId"]) && hasOwn(value, "code") && ((typeof value["code"] === "string")) && hasOwn(value, "message") && ((typeof value["message"] === "string")) && (!hasOwn(value, "fields") || ((isRecord(value["fields"]) && Object.entries(value["fields"]).every(([entry1, item1]) => ((typeof item1 === "string")))))) && hasOwn(value, "requestId") && ((typeof value["requestId"] === "string" && isUuid(value["requestId"])))))
}

export function isApiErrorEnvelope(value: unknown): value is ApiErrorEnvelope {
  return ((isRecord(value) && hasOnlyKeys(value, ["error"]) && hasOwn(value, "error") && isApiError(value["error"])))
}

export function isCategoryResponse(value: unknown): value is CategoryResponse {
  return isCategory(value)
}

export function isCategoryListResponse(value: unknown): value is CategoryListResponse {
  return isCategoryList(value)
}
