// Generated by scripts/generate-reader-types.mjs.
// Source: docs/openapi/reader-v1.json
// DO NOT EDIT MANUALLY. Run `npm run generate:reader-types`.

export type EntryListState = "ALL" | "UNREAD" | "STARRED"

export type PatchEntryStateRequest = {
  isRead?: boolean
  isStarred?: boolean
} & (
  | { isRead: boolean }
  | { isStarred: boolean }
)

export interface EntryPageResponse {
  items: EntryListItemResponse[]
  nextCursor: string | null
  snapshotGeneration: number
}

export interface EntryListItemResponse {
  entryId: string
  feedId: string
  feedTitle: string
  siteUrl: string | null
  title: string | null
  author: string | null
  summary: string | null
  canonicalUrl: string | null
  publishedAtUs: number | null
  sortAtUs: number
  isRead: boolean
  isStarred: boolean
}

export interface EntryDetailResponse {
  entryId: string
  feedId: string
  feedTitle: string
  siteUrl: string | null
  title: string | null
  author: string | null
  summary: string | null
  canonicalUrl: string | null
  publishedAtUs: number | null
  sortAtUs: number
  isRead: boolean
  isStarred: boolean
  contentHtml: string
  inertImages: InertImageResponse[]
  enclosures: EnclosureResponse[]
}

export interface EntryStateResponse {
  entryId: string
  isRead: boolean
  isStarred: boolean
}

export interface InertImageResponse {
  imageIndex: number
  sourceUrl: string
  alt: string | null
  width: number | null
  height: number | null
}

export interface EnclosureResponse {
  url: string
  mediaType: string | null
  length: string | null
  title: string | null
  duration: string | null
}

export interface ErrorEnvelope {
  error: ApiError
}

export interface ApiError {
  code: ApiErrorCode
  message: string
  fields?: Record<string, string>
  requestId: string
}

export type ApiErrorCode = "AUTHENTICATION_REQUIRED" | "FORBIDDEN" | "VALIDATION_ERROR" | "NOT_FOUND" | "INTERNAL_ERROR"

export type ApiErrorEnvelope = ErrorEnvelope

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

function hasOwn(value: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(value, key)
}

function hasOnlyKeys(value: Record<string, unknown>, keys: readonly string[]): boolean {
  return Object.keys(value).every((key) => keys.includes(key))
}

function isUuid(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
}

function isUri(value: string): boolean {
  try {
    return new URL(value).protocol.length > 0
  } catch {
    return false
  }
}

export function isEntryListState(value: unknown): value is EntryListState {
  return (value === "ALL" || value === "UNREAD" || value === "STARRED")
}

export function isPatchEntryStateRequest(value: unknown): value is PatchEntryStateRequest {
  return ((isRecord(value) && hasOnlyKeys(value, ["isRead","isStarred"]) && (!hasOwn(value, "isRead") || (typeof value["isRead"] === "boolean")) && (!hasOwn(value, "isStarred") || (typeof value["isStarred"] === "boolean")))) && ((isRecord(value) && hasOwn(value, "isRead")) || (isRecord(value) && hasOwn(value, "isStarred")))
}

export function isEntryPageResponse(value: unknown): value is EntryPageResponse {
  return ((isRecord(value) && hasOnlyKeys(value, ["items","nextCursor","snapshotGeneration"]) && hasOwn(value, "items") && ((Array.isArray(value["items"]) && value["items"].every((item1) => isEntryListItemResponse(item1)))) && hasOwn(value, "nextCursor") && ((typeof value["nextCursor"] === "string") || value["nextCursor"] === null) && hasOwn(value, "snapshotGeneration") && ((typeof value["snapshotGeneration"] === "number" && Number.isFinite(value["snapshotGeneration"]) && Number.isInteger(value["snapshotGeneration"]) && value["snapshotGeneration"] >= 0))))
}

export function isEntryListItemResponse(value: unknown): value is EntryListItemResponse {
  return ((isRecord(value) && hasOnlyKeys(value, ["entryId","feedId","feedTitle","siteUrl","title","author","summary","canonicalUrl","publishedAtUs","sortAtUs","isRead","isStarred"]) && hasOwn(value, "entryId") && ((typeof value["entryId"] === "string" && isUuid(value["entryId"]))) && hasOwn(value, "feedId") && ((typeof value["feedId"] === "string" && isUuid(value["feedId"]))) && hasOwn(value, "feedTitle") && ((typeof value["feedTitle"] === "string")) && hasOwn(value, "siteUrl") && ((typeof value["siteUrl"] === "string" && isUri(value["siteUrl"])) || value["siteUrl"] === null) && hasOwn(value, "title") && ((typeof value["title"] === "string") || value["title"] === null) && hasOwn(value, "author") && ((typeof value["author"] === "string") || value["author"] === null) && hasOwn(value, "summary") && ((typeof value["summary"] === "string") || value["summary"] === null) && hasOwn(value, "canonicalUrl") && ((typeof value["canonicalUrl"] === "string" && isUri(value["canonicalUrl"])) || value["canonicalUrl"] === null) && hasOwn(value, "publishedAtUs") && ((typeof value["publishedAtUs"] === "number" && Number.isFinite(value["publishedAtUs"]) && Number.isInteger(value["publishedAtUs"])) || value["publishedAtUs"] === null) && hasOwn(value, "sortAtUs") && ((typeof value["sortAtUs"] === "number" && Number.isFinite(value["sortAtUs"]) && Number.isInteger(value["sortAtUs"]))) && hasOwn(value, "isRead") && (typeof value["isRead"] === "boolean") && hasOwn(value, "isStarred") && (typeof value["isStarred"] === "boolean")))
}

export function isEntryDetailResponse(value: unknown): value is EntryDetailResponse {
  return ((isRecord(value) && hasOnlyKeys(value, ["entryId","feedId","feedTitle","siteUrl","title","author","summary","canonicalUrl","publishedAtUs","sortAtUs","isRead","isStarred","contentHtml","inertImages","enclosures"]) && hasOwn(value, "entryId") && ((typeof value["entryId"] === "string" && isUuid(value["entryId"]))) && hasOwn(value, "feedId") && ((typeof value["feedId"] === "string" && isUuid(value["feedId"]))) && hasOwn(value, "feedTitle") && ((typeof value["feedTitle"] === "string")) && hasOwn(value, "siteUrl") && ((typeof value["siteUrl"] === "string" && isUri(value["siteUrl"])) || value["siteUrl"] === null) && hasOwn(value, "title") && ((typeof value["title"] === "string") || value["title"] === null) && hasOwn(value, "author") && ((typeof value["author"] === "string") || value["author"] === null) && hasOwn(value, "summary") && ((typeof value["summary"] === "string") || value["summary"] === null) && hasOwn(value, "canonicalUrl") && ((typeof value["canonicalUrl"] === "string" && isUri(value["canonicalUrl"])) || value["canonicalUrl"] === null) && hasOwn(value, "publishedAtUs") && ((typeof value["publishedAtUs"] === "number" && Number.isFinite(value["publishedAtUs"]) && Number.isInteger(value["publishedAtUs"])) || value["publishedAtUs"] === null) && hasOwn(value, "sortAtUs") && ((typeof value["sortAtUs"] === "number" && Number.isFinite(value["sortAtUs"]) && Number.isInteger(value["sortAtUs"]))) && hasOwn(value, "isRead") && (typeof value["isRead"] === "boolean") && hasOwn(value, "isStarred") && (typeof value["isStarred"] === "boolean") && hasOwn(value, "contentHtml") && ((typeof value["contentHtml"] === "string")) && hasOwn(value, "inertImages") && ((Array.isArray(value["inertImages"]) && value["inertImages"].every((item1) => isInertImageResponse(item1)))) && hasOwn(value, "enclosures") && ((Array.isArray(value["enclosures"]) && value["enclosures"].every((item1) => isEnclosureResponse(item1))))))
}

export function isEntryStateResponse(value: unknown): value is EntryStateResponse {
  return ((isRecord(value) && hasOnlyKeys(value, ["entryId","isRead","isStarred"]) && hasOwn(value, "entryId") && ((typeof value["entryId"] === "string" && isUuid(value["entryId"]))) && hasOwn(value, "isRead") && (typeof value["isRead"] === "boolean") && hasOwn(value, "isStarred") && (typeof value["isStarred"] === "boolean")))
}

export function isInertImageResponse(value: unknown): value is InertImageResponse {
  return ((isRecord(value) && hasOnlyKeys(value, ["imageIndex","sourceUrl","alt","width","height"]) && hasOwn(value, "imageIndex") && ((typeof value["imageIndex"] === "number" && Number.isFinite(value["imageIndex"]) && Number.isInteger(value["imageIndex"]) && value["imageIndex"] >= 0)) && hasOwn(value, "sourceUrl") && ((typeof value["sourceUrl"] === "string" && isUri(value["sourceUrl"]))) && hasOwn(value, "alt") && ((typeof value["alt"] === "string") || value["alt"] === null) && hasOwn(value, "width") && ((typeof value["width"] === "number" && Number.isFinite(value["width"]) && Number.isInteger(value["width"]) && value["width"] >= 0) || value["width"] === null) && hasOwn(value, "height") && ((typeof value["height"] === "number" && Number.isFinite(value["height"]) && Number.isInteger(value["height"]) && value["height"] >= 0) || value["height"] === null)))
}

export function isEnclosureResponse(value: unknown): value is EnclosureResponse {
  return ((isRecord(value) && hasOnlyKeys(value, ["url","mediaType","length","title","duration"]) && hasOwn(value, "url") && ((typeof value["url"] === "string" && isUri(value["url"]))) && hasOwn(value, "mediaType") && ((typeof value["mediaType"] === "string") || value["mediaType"] === null) && hasOwn(value, "length") && ((typeof value["length"] === "string") || value["length"] === null) && hasOwn(value, "title") && ((typeof value["title"] === "string") || value["title"] === null) && hasOwn(value, "duration") && ((typeof value["duration"] === "string") || value["duration"] === null)))
}

export function isErrorEnvelope(value: unknown): value is ErrorEnvelope {
  return ((isRecord(value) && hasOnlyKeys(value, ["error"]) && hasOwn(value, "error") && isApiError(value["error"])))
}

export function isApiError(value: unknown): value is ApiError {
  return ((isRecord(value) && hasOnlyKeys(value, ["code","message","fields","requestId"]) && hasOwn(value, "code") && (value["code"] === "AUTHENTICATION_REQUIRED" || value["code"] === "FORBIDDEN" || value["code"] === "VALIDATION_ERROR" || value["code"] === "NOT_FOUND" || value["code"] === "INTERNAL_ERROR") && hasOwn(value, "message") && ((typeof value["message"] === "string")) && (!hasOwn(value, "fields") || ((isRecord(value["fields"]) && Object.entries(value["fields"]).every(([entry1, item1]) => ((typeof item1 === "string")))))) && hasOwn(value, "requestId") && ((typeof value["requestId"] === "string" && isUuid(value["requestId"])))))
}

export function isApiErrorEnvelope(value: unknown): value is ApiErrorEnvelope {
  return isErrorEnvelope(value)
}
